resolver: lts-8.4

packages:
- '.'
- location:
    git: https://github.com/dybber/cgen
    commit: a34317de48bb93d57ce0deccd778866d4ed50949
  extra-dep: true
  
extra-deps: []
flags: {}
extra-package-dbs: []

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
