resolver: lts-8.4

packages:
- '.'
- location:
    git: https://github.com/dybber/cgen
    commit: 6abd03baed11d9357026122eaf6b6531e57b617f
  extra-dep: true
  
extra-deps: []
flags: {}
extra-package-dbs: []

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
